### ISSUE TITLE
write numerical plot function specifications and documentation

### ISSUE THREAD

**Issue by phchen5** [UBC-MDS/PyXplor#10]

**Comment by iris0614** [comment]
import matplotlib.pyplot as plt
import seaborn as sns

def plot_numerical(input_df, list_of_variables, orientation, fig_width, fig_height, output_path):
    """
    Create univariate exploratory data visualizations for numerical data.

    Parameters
    ----------
    input_df : pandas.DataFrame
        The input dataframe containing the numerical data.
    
    list_of_variables : list of str
        List of numerical variables to be visualized.

    orientation : {"row", "column"}
        Orientation of the subplots. If "row", variables are visualized in a single row.
        If "column", variables are visualized in a single column.

    fig_width : int
        Width of the entire figure in inches.

    fig_height : int
        Height of the entire figure in inches.

    output_path : str
        Filepath to save the generated visualization.

    Returns
    -------
    None
        The function saves the visualization to the specified output_path.

    Examples
    --------
    >>> numerical = ["mean radius", "mean texture", "mean perimeter", "mean area"]
    >>> plot_numerical(df, numerical, "row", 30, 5, "sample.png")
    """

    # Check if the orientation parameter is valid
    if orientation not in ["row", "column"]:
        raise ValueError("Invalid orientation. Use 'row' or 'column'.")

    no_variables = len(list_of_variables)

    if orientation == "row":
        # Create subplots in a single row
        fig, ax = plt.subplots(1, no_variables, figsize=(fig_width, fig_height))

        for i in range(no_variables):
            # Plot histogram for each variable
            sns.histplot(x=list_of_variables[i], data=input_df, ax=ax[i])
            ax[i].set_title(list_of_variables[i])  # Set subplot title
        
        plt.savefig(output_path)  # Save the figure

    elif orientation == "column":
        # Create subplots in a single column
        fig, ax = plt.subplots(no_variables, 1, figsize=(fig_width, fig_height))

        for i in range(no_variables):
            # Plot histogram for each variable
            sns.histplot(x=list_of_variables[i], data=input_df, ax=ax[i])
            ax[i].set_title(list_of_variables[i])  # Set subplot title

        plt.savefig(output_path)  # Save the figure

# Example usage:
numerical = ["mean radius", "mean texture", "mean perimeter", "mean area"]
plot_numerical(df, numerical, "row", 30, 5, "sample.png")
