### ISSUE TITLE
Addressed Feedback

### ISSUE THREAD

**Issue by rbouwer** [UBC-MDS/PyXplor#107]
These commit messages will start with 'ADDRESSED FEEDBACK'

**Comment by phchen5** [comment]
**Addressed Feedbacks and Other Improvements:**

1. Feedback addressed by @phchen5 about simplifying the example demonstration to check if the function works ([b417bd1](https://github.com/UBC-MDS/PyXplor/commit/b417bd1e4e4eeb988441d987078eabbff33e9936))
2. Feedback addressed by @phchen5 about clarifying and updating the installation instructions in the README - suggested by @Marcony1 ([b8a4807](https://github.com/UBC-MDS/PyXplor/commit/b8a4807ed0ee999fe4e01300f3a7c249ecfb3a23))
3. Feedback addressed by @phchen5 about reordering the icons for better visualization ([f382bd8](https://github.com/UBC-MDS/PyXplor/commit/f382bd899688b00d97307fffa3e281ffba473a8b))
4. Feedback addressed by @rbouwer about improving vignette for more details - suggested by @joeywwwu ([3de1c7c](https://github.com/UBC-MDS/PyXplor/commit/3de1c7c6f89bfe2a5f9f4ff0417be703c5822a12))
5. Feedback addressed by @rbouwer about improving `plot_categorical` functionality - suggested by @salva-u ([9d541c3](https://github.com/UBC-MDS/PyXplor/commit/9d541c3867788589a4388343ad2180ca1c3bd3ea))
7. Feedback addressed by @arturoboquin about fixing the python badge version ([ffb8254](https://github.com/UBC-MDS/PyXplor/commit/ffb825443dd7f9983e95ae2aadc47249f921f1fe))
8. Feedback addressed by @arturoboquin about fixing the PyPI link ([5b7c559](https://github.com/UBC-MDS/PyXplor/commit/5b7c559ee5258a2734501f87a7140bb138ae2048))
9. Feedback addressed by @arturoboquin about adding direct link to documentation in the README - suggested by @YimengXia ([e70d1ea](https://github.com/UBC-MDS/PyXplor/commit/e70d1ea9706515fed89277ac7e648bcc6bbe6e33))
11. Feedback addressed by @arturoboquin about adding missing badges - suggested by @Marcony1 ([193637f](https://github.com/UBC-MDS/PyXplor/commit/193637f6016c139665f0a73131e684614a879f89))
12. Feedback addressed by @iris0614 about adding color functionality into `plot_numeric` - suggested by @YimengXia ([88f08d0](https://github.com/UBC-MDS/PyXplor/commit/88f08d071c9050c6bd04a97d82e0b6484b0dddb5) and [b91fad5](https://github.com/UBC-MDS/PyXplor/commit/b91fad59b248b9a67ee11a9cabd21b315f5b2c18))
13. Feedback addressed by @iris0614 about adjusting the default color for `plot_numeric` ([a8c0009](https://github.com/UBC-MDS/PyXplor/commit/a8c000927477b19edf9c7f7eb522cfbb078ed390))
14. Feedback addressed by @iris0614 about removing excess `pyxplor.py` file - suggested by @Marcony1 ([ef02489](https://github.com/UBC-MDS/PyXplor/commit/ef02489f2882f055706d886d8ca016bdb59bbbc4))
