### ISSUE TITLE
Week 2 Minutes

### ISSUE THREAD

**Issue by rbouwer** [UBC-MDS/PyXplor#30]
Function Contents

- [ ] return `fig` and `ax` objects (especially useful for testing)
- [ ] see issue https://github.com/UBC-MDS/PyXplor/issues/29 for example function
- [ ] blue (contrast - orange) color scheme
- [ ] test output save yes/no, test subplot titles (variable name), test number of subplots (and presence of empty plots)
- [ ] Make option whether to save (change output_path parameter to boolean `output_fig` flag - default FALSE)

**Comment by rbouwer** [comment]
Ben's function 
- add subplot titles
- add rows by column code 
- add subplot orientation default as horizontal 
- add relative percentage (as well as counts)

Rachel's function
- add subplot titles
- add rows by column code
- default orientation be horizontal 
- add overall title ("Distribution of Categorical Variables")
- add parameter for "top X" (top number of categories to show)
- maybe error handling for if >10, choose top 10 and display a message

Arturo's function
- add subplot titles
- add overall title ("Distribution of Categorical Variables")
- add error handlng/checking for granularity of data (can only aggregate data (e.g. W->M, M->Y), cannot "go down")
- "stacked" charts

**Comment by iris0614** [comment]
I think we also need to drop 'docs/requirements.txt' (deprecated) according to Tiffany (so i drop it in my branch )

**Comment by iris0614** [comment]
<img width="771" alt="截屏2024-01-15 20 32 21" src="https://github.com/UBC-MDS/PyXplor/assets/143670925/854f2bfc-65f0-42dd-a003-7818fae14e66">

**Comment by iris0614** [comment]
We finish everything!
