### ISSUE TITLE
Week 3 MoM

### ISSUE THREAD

**Issue by rbouwer** [UBC-MDS/PyXplor#70]
- Make sure format is complying with ReadTheDocs standards
- Create a *story* to guide users through how to use our package

Expectations:
- `README` -> polish, add button to README
- ReadTheDocs -> polish docstrings
- Tutorial `ipynb` file -> Real life example: `seaborn` (either `taxis` - https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page ~~or `seaice` - https://nsidc.org/sites/default/files/documents/technical-reference/sea-ice-analysis-spreadsheets-overview.pdf~~)
- GRAMMAR check

Vignette Structure:
- Summary of package
- Data Loading Section
- Functions Overview
- @phchen5 's `plot_binary()`
- @rbouwer 's `plot_categorical()`
- @iris0614 's `plot_numerical()`
- @arturoboquin 's `plot_time_series()`

**Comment by iris0614** [comment]
examples of a Python package good tutorial/vignette:
https://altair-viz.github.io/case_studies/exploring-weather.html
https://matplotlib.org/stable/tutorials/images.html
https://pandas.pydata.org/docs/user_guide/groupby.html

**Comment by iris0614** [comment]
add the ReadtheDocs button to our packages README.md file to indicate the status of the docs and to let users easily find our rendered documentation. We can find this under your project on ReadtheDocs by clicking the "i" icon beside the badge (see image below)
![Screenshot 2024-01-22 at 4 09 59 PM](https://github.com/UBC-MDS/PyXplor/assets/143670925/a9e4235e-795a-4651-9ce1-5f360648bd44)

**Comment by iris0614** [comment]
ReadTheDocs  vs Tutorial ipynb file: Tutorial matters more
