### ISSUE TITLE
Example Structure

### ISSUE THREAD

**Issue by rbouwer** [UBC-MDS/PyXplor#76]
# Tutorial: Exploring `seaborn`'s `taxis` Dataset

*Summary about tutorial purpose*

*Summary about dataset - columns of interest*

```
# Loading the dataset (using `seaborn` - dependency of package)
# show `.head()`
```

*Quick overview of functions*

## Exploring binary features

*Narrative around `plot_binary()`*

## Exploring categorical features

*Narrative around `plot_categorical()`*

## Exploring numeric features

*Narrative around `plot_numerical()`*

## Exploring time series data

*Narrative around `plot_time_series()`*

**Comment by iris0614** [comment]
You are well organized, and thank you for your notes. It is perfect.
