### ISSUE TITLE
readthedocs formatting playground

### ISSUE THREAD

**Issue by phchen5** [UBC-MDS/PyXplor#81]
readthedocs formatting playground: Write and publish the package-level documentation
Your package-level documentation should be very clear and polished by the end of this milestone. It should include a vignette (i.e., an article/tutorial) demonstrating how to use all your package functions on a more real-life example than the examples in the function documentation. There should be clear and well written narrative to go along with the code examples in the vignette. Essentially, this documentations should enable any user with minimal expertise to be able to run your package functions and play around with them.

**Comment by iris0614** [comment]
Yes , it looks good now.
